### ISSUE TITLE
Running on M1/M2 issue

### ISSUE THREAD

**Issue by marcusze** [huridocs/pdf-document-layout-analysis#12]
Hi there,

I've tried to get the docker-compose setup for no_gpu to work on my Mac M1 with Docker Desktop 4.30.0.

Both regular build and using `docker buildx build --platform linux/arm64` result in the following errors on boot:

<img width="847" alt="image" src="https://github.com/huridocs/pdf-document-layout-analysis/assets/4067657/da64e799-8092-4d9b-ad94-74c2c75561f2">

`[ERROR] Worker (pid:##) was sent SIGILL!`

Is there something else I can try?

**Comment by gabriel-piles** [comment]
Hello!

To resolve the issue you're having, please try these steps:

1. Check System Resources: Ensure you have enough available RAM and hard drive space to run the Docker container smoothly.

2. Download Models First: Before starting the container, download the necessary models using the following commands in your terminal:

```
pip install -r requirements.txt
python src/download_models.py
```

```
make start_no_gpu
```

If you still encounter problems after following these steps, please provide more details about the specific error messages you receive. This will help me diagnose the issue more effectively and offer a targeted solution.

Let me know how it goes!
