### ISSUE TITLE
Cannot install -r requirements.txt (line 10), -r requirements.txt (line 13), requests==2.31.0 and timm because these package versions have conflicting dependencies

### ISSUE THREAD

**Issue by so1n** [huridocs/pdf-document-layout-analysis#15]
Hello, I encountered this problem during installation, which prevented me from installing successfully. After checking, I found that requests 2.31.0 has been marked as YANKED.

see: https://pypi.org/project/requests/#history

**Comment by ali6parmak** [comment]
Hi, we have updated the requirements 2 hours ago and are now using requests version 2.32.3. Can you try to pull the latest changes from the repository and attempt the installation again? This should resolve the issue.

**Comment by so1n** [comment]
After trying, the latest version has solved the problem, thank
