### ISSUE TITLE
when i process with  command   make start  but it away apparent the that erro，i have check the Internet of many time ，but it still not work

### ISSUE THREAD

**Issue by Lbaiall** [huridocs/pdf-document-layout-analysis#24]
16.11                  from /app/.venv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/python.h:11,
16.11                  from /app/.venv/lib/python3.10/site-packages/torch/include/torch/extension.h:9,
16.11                  from /app/src/detectron2/detectron2/layers/csrc/vision.cpp:3:
16.11 /app/.venv/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h: In instantiation of ‘class pybind11::class_<detectron2::COCOeval::InstanceAnnotation>’:
16.11 /app/src/detectron2/detectron2/layers/csrc/vision.cpp:105:73:   required from here
16.11 /app/.venv/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h:1555:7: warning: ‘pybind11::class_<detectron2::COCOeval::InstanceAnnotation>’ declared with greater visibility than its base ‘pybind11::detail::generic_type’ [-Wattributes]
16.11  1555 | class class_ : public detail::generic_type {
16.11       |       ^~~~~~
16.11 /app/.venv/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h: In instantiation of ‘class pybind11::class_<detectron2::COCOeval::ImageEvaluation>’:
16.11 /app/src/detectron2/detectron2/layers/csrc/vision.cpp:107:67:   required from here
16.11 /app/.venv/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h:1555:7: warning: ‘pybind11::class_<detectron2::COCOeval::ImageEvaluation>’ declared with greater visibility than its base ‘pybind11::detail::generic_type’ [-Wattributes]
16.11 g++ -pthread -B /opt/conda/compiler_compat -shared -Wl,-rpath,/opt/conda/lib -Wl,-rpath-link,/opt/conda/lib -L/opt/conda/lib -Wl,-rpath,/opt/conda/lib -Wl,-rpath-link,/opt/conda/lib -L/opt/conda/lib /app/src/detectron2/build/temp.linux-x86_64-cpython-310/app/src/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.o /app/src/detectron2/build/temp.linux-x86_64-cpython-310/app/src/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cpu.o /app/src/detectron2/build/temp.linux-x86_64-cpython-310/app/src/detectron2/detectron2/layers/csrc/cocoeval/cocoeval.o /app/src/detectron2/build/temp.linux-x86_64-cpython-310/app/src/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.o /app/src/detectron2/build/temp.linux-x86_64-cpython-310/app/src/detectron2/detectron2/layers/csrc/vision.o -L/app/.venv/lib/python3.10/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-cpython-310/detectron2/_C.cpython-310-x86_64-linux-gnu.so
16.30 running develop
16.30 /app/.venv/lib/python3.10/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
16.30 !!
16.30
16.30         ********************************************************************************
16.30         Please avoid running ``setup.py`` and ``easy_install``.
16.30         Instead, use pypa/build, pypa/installer or other
16.30         standards-based tools.
16.30
16.30         See https://github.com/pypa/setuptools/issues/917 for details.
16.30         ********************************************************************************
16.30
16.30 !!
16.30   easy_install.initialize_options(self)
16.31 /app/.venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
16.31 !!
16.31
16.31         ********************************************************************************
16.31         Please avoid running ``setup.py`` directly.
16.31         Instead, use pypa/build, pypa/installer or other
16.31         standards-based tools.
16.31
16.31         See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
16.31         ********************************************************************************
16.31
16.31 !!
16.31   self.initialize_options()
16.34 running egg_info
16.34 creating detectron2.egg-info
16.34 writing detectron2.egg-info/PKG-INFO
16.34 writing dependency_links to detectron2.egg-info/dependency_links.txt
16.34 writing requirements to detectron2.egg-info/requires.txt
16.34 writing top-level names to detectron2.egg-info/top_level.txt
16.34 writing manifest file 'detectron2.egg-info/SOURCES.txt'
16.35 reading manifest file 'detectron2.egg-info/SOURCES.txt'
16.35 adding license file 'LICENSE'
16.35 writing manifest file 'detectron2.egg-info/SOURCES.txt'
16.35 running build_ext
16.36 building 'detectron2._C' extension
16.36 Emitting ninja build file /app/src/detectron2/build/temp.linux-x86_64-cpython-310/build.ninja...
16.36 Compiling objects...
16.36 Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
19.86 [1/5] c++ -MMD -MF /app/src/detectron2/build/temp.linux-x86_64-cpython-310/app/src/detectron2/detectron2/layers/csrc/cocoeval/cocoeval.o.d -pthread -B /opt/conda/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/conda/include -fPIC -O2 -isystem /opt/conda/include -fPIC -I/app/src/detectron2/detectron2/layers/csrc -I/app/.venv/lib/python3.10/site-packages/torch/include -I/app/.venv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/app/.venv/lib/python3.10/site-packages/torch/include/TH -I/app/.venv/lib/python3.10/site-packages/torch/include/THC -I/app/.venv/include -I/opt/conda/include/python3.10 -c -c /app/src/detectron2/detectron2/layers/csrc/cocoeval/cocoeval.cpp -o /app/src/detectron2/build/temp.linux-x86_64-cpython-310/app/src/detectron2/detectron2/layers/csrc/cocoeval/cocoeval.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
21.03 [2/5] c++ -MMD -MF /app/src/detectron2/build/temp.linux-x86_64-cpython-310/app/src/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cpu.o.d -pthread -B /opt/conda/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/conda/include -fPIC -O2 -isystem /opt/conda/include -fPIC -I/app/src/detectron2/detectron2/layers/csrc -I/app/.venv/lib/python3.10/site-packages/torch/include -I/app/.venv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/app/.venv/lib/python3.10/site-packages/torch/include/TH -I/app/.venv/lib/python3.10/site-packages/torch/include/THC -I/app/.venv/include -I/opt/conda/include/python3.10 -c -c /app/src/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cpu.cpp -o /app/src/detectron2/build/temp.linux-x86_64-cpython-310/app/src/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
21.06 [3/5] c++ -MMD -MF /app/src/detectron2/build/temp.linux-x86_64-cpython-310/app/src/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.o.d -pthread -B /opt/conda/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/conda/include -fPIC -O2 -isystem /opt/conda/include -fPIC -I/app/src/detectron2/detectron2/layers/csrc -I/app/.venv/lib/python3.10/site-packages/torch/include -I/app/.venv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/app/.venv/lib/python3.10/site-packages/torch/include/TH -I/app/.venv/lib/python3.10/site-packages/torch/include/THC -I/app/.venv/include -I/opt/conda/include/python3.10 -c -c /app/src/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp -o /app/src/detectron2/build/temp.linux-x86_64-cpython-310/app/src/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
21.62 [4/5] c++ -MMD -MF /app/src/detectron2/build/temp.linux-x86_64-cpython-310/app/src/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.o.d -pthread -B /opt/conda/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/conda/include -fPIC -O2 -isystem /opt/conda/include -fPIC -I/app/src/detectron2/detectron2/layers/csrc -I/app/.venv/lib/python3.10/site-packages/torch/include -I/app/.venv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/app/.venv/lib/python3.10/site-packages/torch/include/TH -I/app/.venv/lib/python3.10/site-packages/torch/include/THC -I/app/.venv/include -I/opt/conda/include/python3.10 -c -c /app/src/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.cpp -o /app/src/detectron2/build/temp.linux-x86_64-cpython-310/app/src/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
29.16 [5/5] c++ -MMD -MF /app/src/detectron2/build/temp.linux-x86_64-cpython-310/app/src/detectron2/detectron2/layers/csrc/vision.o.d -pthread -B /opt/conda/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/conda/include -fPIC -O2 -isystem /opt/conda/include -fPIC -I/app/src/detectron2/detectron2/layers/csrc -I/app/.venv/lib/python3.10/site-packages/torch/include -I/app/.venv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/app/.venv/lib/python3.10/site-packages/torch/include/TH -I/app/.venv/lib/python3.10/site-packages/torch/include/THC -I/app/.venv/include -I/opt/conda/include/python3.10 -c -c /app/src/detectron2/detectron2/layers/csrc/vision.cpp -o /app/src/detectron2/build/temp.linux-x86_64-cpython-310/app/src/detectron2/detectron2/layers/csrc/vision.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
29.16 In file included from /app/.venv/lib/python3.10/site-packages/torch/include/torch/csrc/Exceptions.h:12,
29.16                  from /app/.venv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/python.h:11,
29.16                  from /app/.venv/lib/python3.10/site-packages/torch/include/torch/extension.h:9,
29.16                  from /app/src/detectron2/detectron2/layers/csrc/vision.cpp:3:
29.16 /app/.venv/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h: In instantiation of ‘class pybind11::class_<detectron2::COCOeval::InstanceAnnotation>’:
29.16 /app/src/detectron2/detectron2/layers/csrc/vision.cpp:105:73:   required from here
29.16 /app/.venv/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h:1555:7: warning: ‘pybind11::class_<detectron2::COCOeval::InstanceAnnotation>’ declared with greater visibility than its base ‘pybind11::detail::generic_type’ [-Wattributes]
29.16  1555 | class class_ : public detail::generic_type {
29.16       |       ^~~~~~
29.16 /app/.venv/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h: In instantiation of ‘class pybind11::class_<detectron2::COCOeval::ImageEvaluation>’:
29.16 /app/src/detectron2/detectron2/layers/csrc/vision.cpp:107:67:   required from here
29.16 /app/.venv/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h:1555:7: warning: ‘pybind11::class_<detectron2::COCOeval::ImageEvaluation>’ declared with greater visibility than its base ‘pybind11::detail::generic_type’ [-Wattributes]
29.16 g++ -pthread -B /opt/conda/compiler_compat -shared -Wl,-rpath,/opt/conda/lib -Wl,-rpath-link,/opt/conda/lib -L/opt/conda/lib -Wl,-rpath,/opt/conda/lib -Wl,-rpath-link,/opt/conda/lib -L/opt/conda/lib /app/src/detectron2/build/temp.linux-x86_64-cpython-310/app/src/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.o /app/src/detectron2/build/temp.linux-x86_64-cpython-310/app/src/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cpu.o /app/src/detectron2/build/temp.linux-x86_64-cpython-310/app/src/detectron2/detectron2/layers/csrc/cocoeval/cocoeval.o /app/src/detectron2/build/temp.linux-x86_64-cpython-310/app/src/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.o /app/src/detectron2/build/temp.linux-x86_64-cpython-310/app/src/detectron2/detectron2/layers/csrc/vision.o -L/app/.venv/lib/python3.10/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-cpython-310/detectron2/_C.cpython-310-x86_64-linux-gnu.so
29.33 copying build/lib.linux-x86_64-cpython-310/detectron2/_C.cpython-310-x86_64-linux-gnu.so -> detectron2
29.33 Creating /app/.venv/lib/python3.10/site-packages/detectron2.egg-link (link to .)
29.33 Adding detectron2 0.6 to easy-install.pth file
29.33
29.33 Installed /app/src/detectron2
29.33 Processing dependencies for detectron2==0.6
29.34 Searching for black
29.34 Reading https://pypi.org/simple/black/
32.25 Downloading https://files.pythonhosted.org/packages/e0/7d/7f8df0fdbbbefc4362d3eca6b69b7a8a4249a8a88dabc00a207d31fddcd7/black-24.4.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=eaea3008c281f1038edb473c1aa8ed8143a5535ff18f978a318f10302b254063
35.56 Best match: black 24.4.2
35.56 Processing black-24.4.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
35.56 Installing black-24.4.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl to /app/.venv/lib/python3.10/site-packages
35.60 Adding black 24.4.2 to easy-install.pth file
35.60 Installing black script to /app/.venv/bin
35.60 Installing blackd script to /app/.venv/bin
35.60
35.60 Installed /app/.venv/lib/python3.10/site-packages/black-24.4.2-py3.10-linux-x86_64.egg
35.60 Searching for hydra-core>=1.1
35.60 Reading https://pypi.org/simple/hydra-core/
37.76 Downloading https://files.pythonhosted.org/packages/c6/50/e0edd38dcd63fb26a8547f13d28f7a008bc4a3fd4eb4ff030673f22ad41a/hydra_core-1.3.2-py3-none-any.whl#sha256=fa0238a9e31df3373b35b0bfb672c34cc92718d21f81311d8996a16de1141d8b
39.12 Best match: hydra-core 1.3.2
39.12 Processing hydra_core-1.3.2-py3-none-any.whl
39.13 Installing hydra_core-1.3.2-py3-none-any.whl to /app/.venv/lib/python3.10/site-packages
39.15 Adding hydra-core 1.3.2 to easy-install.pth file
39.15 detected new path './black-24.4.2-py3.10-linux-x86_64.egg'
39.15
39.15 Installed /app/.venv/lib/python3.10/site-packages/hydra_core-1.3.2-py3.10.egg
39.15 Searching for omegaconf<2.4,>=2.1
39.15 Reading https://pypi.org/simple/omegaconf/
40.79 Downloading https://files.pythonhosted.org/packages/e3/94/1843518e420fa3ed6919835845df698c7e27e183cb997394e4a670973a65/omegaconf-2.3.0-py3-none-any.whl#sha256=7b4df175cdb08ba400f45cae3bdcae7ba8365db4d165fc65fd04b050ab63b46b
45.98 Best match: omegaconf 2.3.0
45.98 Processing omegaconf-2.3.0-py3-none-any.whl
45.98 Installing omegaconf-2.3.0-py3-none-any.whl to /app/.venv/lib/python3.10/site-packages
46.00 Adding omegaconf 2.3.0 to easy-install.pth file
46.00 detected new path './hydra_core-1.3.2-py3.10.egg'
46.00
46.00 Installed /app/.venv/lib/python3.10/site-packages/omegaconf-2.3.0-py3.10.egg
46.00 Searching for iopath<0.1.10,>=0.1.7
46.00 Reading https://pypi.org/simple/iopath/
46.68 Downloading https://files.pythonhosted.org/packages/af/20/65dd9bd25a1eb7fa35b5ae38d289126af065f8a0c1f6a90564f4bff0f89d/iopath-0.1.9-py3-none-any.whl#sha256=9058ac24f0328decdf8dbe209b33074b8702a3c4d9ba2f7801d46cb61a880b6e
47.97 Best match: iopath 0.1.9
47.97 Processing iopath-0.1.9-py3-none-any.whl
47.97 Installing iopath-0.1.9-py3-none-any.whl to /app/.venv/lib/python3.10/site-packages
47.98 Adding iopath 0.1.9 to easy-install.pth file
47.98 detected new path './omegaconf-2.3.0-py3.10.egg'
47.98
47.98 Installed /app/.venv/lib/python3.10/site-packages/iopath-0.1.9-py3.10.egg
47.98 Searching for fvcore<0.1.6,>=0.1.5
47.98 Reading https://pypi.org/simple/fvcore/
51.06 Downloading https://files.pythonhosted.org/packages/a5/93/d056a9c4efc6c79ba7b5159cc66bb436db93d2cc46dca18ed65c59cc8e4e/fvcore-0.1.5.post20221221.tar.gz#sha256=f2fb0bb90572ae651c11c78e20493ed19b2240550a7e4bbb2d6de87bdd037860
56.10 error: Download error for https://files.pythonhosted.org/packages/a5/93/d056a9c4efc6c79ba7b5159cc66bb436db93d2cc46dca18ed65c59cc8e4e/fvcore-0.1.5.post20221221.tar.gz#sha256=f2fb0bb90572ae651c11c78e20493ed19b2240550a7e4bbb2d6de87bdd037860: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)
------
failed to solve: process "/bin/sh -c cd src/detectron2; python setup.py build develop" did not complete successfully: exit code: 1
make: *** [Makefile:26: start] Error 17

**Comment by ali6parmak** [comment]
Hi,
This looks like a connection error. Please ensure that your internet connection is stable and try to run "make start" again. If it continues to break, please try to check if you are getting completely the same error message. Because in the case of connection related errors, they should be different. In that case, you can try to run "make start" until the program starts.
