### ISSUE TITLE
where can i turn it into the markdown format by process step with json 

### ISSUE THREAD

**Issue by Lbaiall** [huridocs/pdf-document-layout-analysis#25]

**Comment by Lbaiall** [comment]
where i can type my example pdf file ......  
docker compose -f docker-compose-gpu.yml up --build
[+] Building 7.1s (22/22) FINISHED                                                                       docker:default
 => [pdf-document-layout-analysis-gpu internal] load build definition from Dockerfile                              0.0s
 => => transferring dockerfile: 933B                                                                               0.0s
 => [pdf-document-layout-analysis-gpu internal] load metadata for docker.io/pytorch/pytorch:2.3.1-cuda11.8-cudnn8  7.0s
 => [pdf-document-layout-analysis-gpu internal] load .dockerignore                                                 0.0s
 => => transferring context: 81B                                                                                   0.0s
 => [pdf-document-layout-analysis-gpu  1/17] FROM docker.io/pytorch/pytorch:2.3.1-cuda11.8-cudnn8-runtime@sha256:  0.0s
 => [pdf-document-layout-analysis-gpu internal] load build context                                                 0.0s
 => => transferring context: 1.83kB                                                                                0.0s
 => CACHED [pdf-document-layout-analysis-gpu  2/17] RUN apt-get update                                             0.0s
 => CACHED [pdf-document-layout-analysis-gpu  3/17] RUN apt-get install -y -q --no-install-recommends libgomp1 ff  0.0s
 => CACHED [pdf-document-layout-analysis-gpu  4/17] RUN mkdir -p /app/src                                          0.0s
 => CACHED [pdf-document-layout-analysis-gpu  5/17] RUN mkdir -p /app/models                                       0.0s
 => CACHED [pdf-document-layout-analysis-gpu  6/17] RUN addgroup --system python && adduser --system --group pyth  0.0s
 => CACHED [pdf-document-layout-analysis-gpu  7/17] RUN chown -R python:python /app                                0.0s
 => CACHED [pdf-document-layout-analysis-gpu  8/17] RUN python -m venv /app/.venv                                  0.0s
 => CACHED [pdf-document-layout-analysis-gpu  9/17] COPY requirements.txt requirements.txt                         0.0s
 => CACHED [pdf-document-layout-analysis-gpu 10/17] RUN pip install --upgrade pip                                  0.0s
 => CACHED [pdf-document-layout-analysis-gpu 11/17] RUN pip --default-timeout=1000 install -r requirements.txt     0.0s
 => CACHED [pdf-document-layout-analysis-gpu 12/17] WORKDIR /app                                                   0.0s
 => CACHED [pdf-document-layout-analysis-gpu 13/17] RUN cd src; git clone https://github.com/facebookresearch/det  0.0s
 => CACHED [pdf-document-layout-analysis-gpu 14/17] RUN cd src/detectron2; python setup.py build develop           0.0s
 => CACHED [pdf-document-layout-analysis-gpu 15/17] COPY ./src/. ./src                                             0.0s
 => CACHED [pdf-document-layout-analysis-gpu 16/17] COPY ./models/. ./models/                                      0.0s
 => CACHED [pdf-document-layout-analysis-gpu 17/17] RUN python src/download_models.py                              0.0s
 => [pdf-document-layout-analysis-gpu] exporting to image                                                          0.0s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:58b57dbfb1ab143e16f114f3fd373038dc83b6d8649e393c818c6d236b11bb3d                       0.0s
 => => naming to docker.io/library/pdf-document-layout-analysis-pdf-document-layout-analysis-gpu                   0.0s
[+] Running 1/0
 ✔ Container pdf-document-layout-analysis  Running                                                                 0.0s
Attaching to pdf-document-layout-analysis



v View in Docker Desktop      w Enable Watch

**Comment by gabriel-piles** [comment]
Thank you for your question. 

We apologize, but we do not currently support Markdown formatting.
