### ISSUE TITLE
Update model links in "download_models.py"

### ISSUE THREAD

**Issue by Mengqi925** [huridocs/pdf-document-layout-analysis#40]
I found that the download link of "_vgt_model" in "download_model.py" (https://github.com/AlibabaResearch/AdvancedLiterateMachinery/releases/download/v1.3.0-VGT-release) cannot open.
I think this one should be right:
https://github.com/AlibabaResearch/AdvancedLiterateMachinery/releases/tag/v1.3.0-VGT-release
Please check and update if necessary.

In addtion, I noticed that "microsoft/layoutlmv-base-uncased" has been improved to a new version→https://huggingface.co/microsoft/layoutlmv2-base-uncased

Thank you!

**Comment by gabriel-piles** [comment]
Thank you for contacting us. We understand that some users are experiencing difficulties downloading our models. I've tested the download process myself today, and it appears to be working correctly on my end. Please try downloading the model again. If you continue to encounter issues, please let us know, and we'll be happy to provide updated download links.

Regarding LayoutLM, retraining the model is not a high priority for us at this time. As we are not the original authors of the VGT model, retraining would require significant effort and time.
