### ISSUE TITLE
Is there support for running the model on multiple GPUs?

### ISSUE THREAD

**Issue by dmakwana** [huridocs/pdf-document-layout-analysis#55]
As described here: https://huggingface.co/docs/diffusers/en/training/distributed_inference#pytorch-distributed

Has it been tested? I'm wondering what the best way to do this is. Any suggestions / pointers would be greatly appreciated.

cc: @wrose100

**Comment by gabriel-piles** [comment]
Hello, thanks for your interest in the project.

Our model run on a single GPU with less than 8GB of memory, making it suitable for most standard use cases. If you're looking to process a high volume of PDFs, we recommend exploring parallel processing using multiple Docker containers.

To provide the most effective solution, please share more details about your specific use case, including the expected PDF volume, processing requirements, and desired throughput.

We're happy to assist you in finding the optimal configuration for your needs.

**Comment by rogoit** [comment]
Maybe this is related on a ubuntu linux system

Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]

**Comment by gabriel-piles** [comment]
@rogoit  

Thank you for your question!

It's possible that the issue might be related to the NVIDIA Container Toolkit.  If you haven't already, you can install it by following the official NVIDIA guide: [link to NVIDIA Container Toolkit installation guide](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html).  Alternatively, if you have the toolkit installed, reinstalling it might resolve any potential conflicts.   

Let me know if you try either of these suggestions and still encounter problems.

**Comment by rogoit** [comment]
Hi @gabriel-piles ,

thx for response. The thing is that we will not have invidia drivers or any kind of grafic interface in our it infrastructure for the project or on local environments. So why do you need this?

See you
Roland

**Comment by gabriel-piles** [comment]
hi @rogoit,

In that case, start the docker container with:

```
make start_no_gpu
```

Please let us know if you have any further questions.

**Comment by rogoit** [comment]
Ok, i will check on weekend I hope. Thx for your passion.
