### ISSUE TITLE
Visualisations in README: how were they created?

### ISSUE THREAD

**Issue by vadim0x60** [huridocs/pdf-document-layout-analysis#65]
I would like to visualize segmentations of my PDFs similarly to the examples in README (`vgtexample{1-4}.pdf`). What code was used to make those visualizations?

**Comment by ali6parmak** [comment]
Hi,

I have added the code for visualizations. Please pull the changes and try to run this command:

```
curl -X POST -F 'file=@/PATH/TO/PDF/pdf_name.pdf' localhost:5060/visualize -o 'file=@/PATH/TO/OUTPUT_PDF/pdf_name.pdf'
```

Or if you want to use fast models while getting the visualizations:

```
curl -X POST -F 'file=@/PATH/TO/PDF/pdf_name.pdf' -F "fast=true" localhost:5060/visualize -o 'file=@/PATH/TO/OUTPUT_PDF/pdf_name.pdf'
```
You can reach out if you need anything else!

**Comment by vadim0x60** [comment]
Thank you!
