### ISSUE TITLE
Stand this up as a docker image on dockerhub for others to use?

### ISSUE THREAD

**Issue by GullyBurns** [huridocs/pdf-document-layout-analysis#77]
Would it be possible to create a docker image on DockerHub that members of the community could use in their `docker-compose` statements?

**Comment by gabriel-piles** [comment]
Hi @GullyBurns ,

Thank you for your feedback. We're definitely interested in exploring the benefits of publishing our images on DockerHub. While we've been using GitHub Registry (https://github.com/huridocs/pdf-document-layout-analysis/pkgs/container/pdf-document-layout-analysis), we agree that Docker Hub can enhance accessibility and discoverability.

I'll make sure to familiarize myself with the process next week so we can determine a timeline for the transition.

Thanks again for your input!

**Comment by ali6parmak** [comment]
We have uploaded the docker image into DockerHub, can be found here: https://hub.docker.com/r/huridocs/pdf-document-layout-analysis/

Thanks for your input!
