### ISSUE TITLE
Finetune LightGBM model

### ISSUE THREAD

**Issue by NNDam** [huridocs/pdf-document-layout-analysis#79]
First, thanks for your great work !
I'm using LightGBM version and it's quiet good. But there are still some cases have wrong segmentation (merge different lines together or wrong split). I would like to finetune this segmentation model by adding my custom data (lots of PDF files). Could you provide more detail about training/finetuning your LightGBM model and add customize dataset ?

**Comment by gabriel-piles** [comment]
We have this item in the backlog and will address it in the near future

**Comment by ali6parmak** [comment]
@NNDam We have added a Jupyter notebook to provide support for fine-tuning our models [here](https://github.com/huridocs/pdf-document-layout-analysis/blob/main/fine_tuning_lightgbm_models.ipynb). If you have any questions, do not hesitate to reach.
