### ISSUE TITLE
Parallel execution

### ISSUE THREAD

**Issue by MaksymBerezovskyiGL** [huridocs/pdf-document-layout-analysis#97]
Is there a convenient way to execute the analysis in parallel or concurrently? 
So far I was only able to execute requests sequentially

**Comment by gabriel-piles** [comment]
Thank you for reaching out. 

You can make parallel requests to the service and even start several services in parallel by changing the port as follows:

docker run --rm --name pdf-document-layout-analysis-[NEW PORT] -p [NEW PORT]:5060 --entrypoint ./start.sh huridocs/pdf-document-layout-analysis:v0.0.19
